blueprint:
  name: ZHA Zigbee Button
  description: >
    Set up automated actions for multiple ZHA Zigbee buttons with 3-mode options: single press, double press and long press.


      ## ⚠️ Attention ⚠️

      - At least one ZHA button must be selected.
      - At least one action (single, double or long press) must be set.
  domain: automation
  input:
    zha_button_ids:
      name: ZHA Buttons
      description: List of ZHA buttons that automations will run for
      selector:
        device:
          integration: zha
          multiple: true
    single_press_actions:
      name: Single press actions (Optional)
      description: Action to perform on single press; can be multiple
      default: []
      selector:
        action: {}
    double_press_actions:
      name: Double press actions (Optional)
      description: Action to perform on double press; can be multiple
      default: []
      selector:
        action: {}
    long_press_actions:
      name: Long press actions (Optional)
      description: Action to perform on long press (over 3 seconds); can be multiple
      default: []
      selector:
        action: {}
  source_url: https://github.com/msx2/home_assistant_blueprints/blob/main/zha_zigbee_button.yaml

variables:
  zha_button_ids: !input 'zha_button_ids'
  single_press_actions: !input 'single_press_actions'
  double_press_actions: !input 'double_press_actions'
  long_press_actions: !input 'long_press_actions'

trigger:
- platform: event
  event_type: zha_event

condition:
- condition: template
  value_template: "{{ trigger.event.data.device_id in zha_button_ids }}"

action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "toggle" }}'
    sequence: !input 'single_press_actions'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "on" }}'
    sequence: !input 'double_press_actions'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "off" }}'
    sequence: !input 'long_press_actions'

